### ISSUE TITLE
 java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by unlying** [gideros/gideros#311]
`java.lang.IllegalArgumentException: No config chosen
	at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:781)
	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:926)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1292)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1146)
![image 1](https://cloud.githubusercontent.com/assets/11470069/24577999/802f57fa-16e0-11e7-9d65-322c57e98a5b.png)
`

**Comment by hgy29** [comment]
Fixed in 501a4be5a7eacdfa3e64a3b38d55eddf86586f0d
