### ISSUE TITLE
 java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by unlying** [gideros/gideros#312]
`java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.debia.associate2/com.giderosmobile.android.associate2Activity}: java.lang.ClassNotFoundException: Didn't find class "com.giderosmobile.android.associate2Activity" on path: DexPathList[[zip file "/mnt/asec/com.debia.associate2-1/pkg.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
	at android.app.ActivityThread.access$900(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.giderosmobile.android.associate2Activity" on path: DexPathList[[zip file "/mnt/asec/com.debia.associate2-1/pkg.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2297)
	... 11 more
	Suppressed: java.io.IOException: unable to open DEX file
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:309)
		at dalvik.system.DexFile.<init>(DexFile.java:82)
		at dalvik.system.DexFile.<init>(DexFile.java:61)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:263)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:230)
		at dalvik.system.DexPathList.<init>(DexPathList.java:112)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:58)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:57)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:326)
		at android.app.LoadedApk.makeApplication(LoadedApk.java:508)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4703)
		at android.app.ActivityThread.access$1600(ActivityThread.java:175)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
		... 8 more
`
![image 2](https://cloud.githubusercontent.com/assets/11470069/24578027/d90a7558-16e0-11e7-857d-23ec08284c0b.png)

**Comment by hgy29** [comment]
do this app run at all ? because the crash says that android doesn't even find the app entry point

**Comment by unlying** [comment]
Have no idea:( 
But it happens only on Android 4.4
I have 12 such crashes now

**Comment by hgy29** [comment]
Closing as stale
