### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by unlying** [gideros/gideros#313]
`java.lang.ExceptionInInitializerError
	at java.lang.Class.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1319)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1071)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2309)
	at android.app.ActivityThread.access$700(ActivityThread.java:157)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5317)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsatisfiedLinkError: Couldn't load gvfs from loader dalvik.system.PathClassLoader[dexPath=/mnt/asec/com.debia.associate2-1/pkg.apk,libraryPath=/mnt/asec/com.debia.associate2-1/lib]: findLibrary returned null
	at java.lang.Runtime.loadLibrary(Runtime.java:365)
	at java.lang.System.loadLibrary(System.java:535)
	at com.giderosmobile.android.associate2Activity.<clinit>(associate2Activity.java:39)
	... 15 more`

![image 3](https://cloud.githubusercontent.com/assets/11470069/24578047/32a7d4d4-16e1-11e7-9f09-74af0353b0e3.png)

**Comment by hgy29** [comment]
Can you post the full log ? it was cut right at the point where it began to be interesting...

**Comment by unlying** [comment]
According to user reviews - this crash doesn't allow them to start a game.

I don't have full logs, but can post some more:

`java.lang.UnsatisfiedLinkError: Couldn't load gvfs from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/mnt/asec/com.debia.associate2-1/pkg.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]: findLibrary returned null
	at java.lang.Runtime.loadLibrary(Runtime.java:365)
	at java.lang.System.loadLibrary(System.java:553)
	at com.giderosmobile.android.associate2Activity.<clinit>(associate2Activity.java:39)
	at java.lang.Class.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1215)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2255)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)`

`java.lang.ExceptionInInitializerError
	at java.lang.Class.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1319)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1057)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2120)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2253)
	at android.app.ActivityThread.access$600(ActivityThread.java:145)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1251)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5119)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:834)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1604): missing essential tables
	at java.lang.Runtime.loadLibrary(Runtime.java:371)
	at java.lang.System.loadLibrary(System.java:535)
	at com.giderosmobile.android.associate2Activity.<clinit>(associate2Activity.java:39)`

`java.lang.UnsatisfiedLinkError: Couldn't load gvfs from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/mnt/asec/com.debia.associate2-1/pkg.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]: findLibrary returned null
	at java.lang.Runtime.loadLibrary(Runtime.java:358)
	at java.lang.System.loadLibrary(System.java:526)
	at com.giderosmobile.android.associate2Activity.<clinit>(associate2Activity.java:39)
	at java.lang.Class.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1208)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
	at android.app.ActivityThread.access$800(ActivityThread.java:166)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5590)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
	at dalvik.system.NativeStart.main(Native Method)`

**Comment by hgy29** [comment]
So what it tells us is that gideros libs aren't bundled into APK, but since thats impossible since it works on other devices then maybe those devices require libs for some specific CPU (mips ?) or they are 64 bit and some plugin included a 64 bit lib.
I ran into a similar issue not long ago on a 64 bit phone, Android considers that if the 64 bit lib dir exists, then all libs must be 64bit, however gideros only provide 32 bit libs. Gideros 2017.6 will have mips support and provide 64 bit versions of the libs, it may fix this issue.

**Comment by hgy29** [comment]
Closing this since it shall have been fixed with support for 64 bit libs on Android. Feel free to reopen if it happens again.
