### ISSUE TITLE
com.giderosmobile.android.player.LuaException

### ISSUE THREAD

**Issue by unlying** [gideros/gideros#316]
`com.giderosmobile.android.player.LuaException: main.lua: bad integer in precompiled chunk
	at com.giderosmobile.android.player.GiderosApplication.throwLuaException(GiderosApplication.java:1235)
	at com.giderosmobile.android.player.GiderosApplication.nativeDrawFrame(Native Method)
	at com.giderosmobile.android.player.GiderosApplication.onDrawFrame(GiderosApplication.java:669)
	at com.giderosmobile.android.GiderosRenderer.onDrawFrame(associate2Activity.java:369)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

`

![image 4](https://cloud.githubusercontent.com/assets/11470069/24768720/4bfe6db0-1b0c-11e7-83af-730c9ab677b2.png)

**Comment by hgy29** [comment]
This message almost always means that your code hasn't been encrypted with the same key as gideros libs, which should never happen on a full export. Can you double check your export ?

**Comment by hgy29** [comment]
No answer on this for more than one year, I assume it is either fixed or no longer relevant. Feel free to reopen if needed.
