### ISSUE TITLE
Android crashes on 2018.10

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#444]
I released four games with Gideros 2018.10 last week. All of them keep getting these crashes (neatly reported by Firebase):

```
Fatal Exception: java.lang.IllegalArgumentException: No config chosen
       at com.giderosmobile.android.player.GiderosConfigChooser.chooseConfig(GiderosConfigChooser.java:68)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

```

```
Fatal Exception: java.lang.IllegalArgumentException: data eglChooseConfig failed
       at com.giderosmobile.android.player.GiderosConfigChooser.chooseConfig(GiderosConfigChooser.java:35)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

```

**Comment by hgy29** [comment]
Those means the device doesn’t meet gideros requirements regarding OpenGL

Envoyé de mon iPhone

**Comment by totebo** [comment]
Is there anything I can do about it?

**Comment by totebo** [comment]
Looking through the devices reporting the error it might not be a big issue; only two "devices" one being "AOSP on ARM Emulator" and the other Nexus 4. The emulator could be Google's own tests device.

**Comment by hgy29** [comment]
I wonder what we should do if we detect an incompatible device ?

**Comment by totebo** [comment]
Is it a brick wall (the game cannot be shown) or could the game be
displayed in a different way?

I'm guessing brick wall, in which case it would be nice to catch this and
deal with it gracefully.

**Comment by hgy29** [comment]
it really depends on what feature is missing in that case, but gideros ask for the minimum configuration allowing to use all features. Given the low number of unsupported devices, I think we shouldn't bother too much. Maybe open an alert dialog saying that the phone isn't supported and exit the app anyway ?

**Comment by totebo** [comment]
Would be nice to gracefully catch this in Lua somehow, to avoid crash at least.

**Comment by hgy29** [comment]
It's been a long time I didn't have such problem reported in my own apps, so I'll close this. Anyway the issue can't be caught in lua, and best we can do is display a native android dialog to tell the user about it.
